#!/usr/bin/env python3
import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT / 'spec/publisher/openapi.json'
CHECKLIST = ROOT / 'spec/publisher/conformance-checklist.json'
OUTPUT = ROOT / 'spec/generated/publisher-profile-fragment.yaml'


def load_json(path: Path) -> dict:
    if not path.exists():
        raise SystemExit(f'missing required file: {path}')
    return json.loads(path.read_text())


def load_openapi_ops(data: dict) -> dict[str, dict[str, str]]:
    ops: dict[str, dict[str, str]] = {}
    for path, methods in data.get('paths', {}).items():
        for method, operation in methods.items():
            if not isinstance(operation, dict):
                continue
            rpc = operation.get('x-tea-proto-rpc')
            if not rpc:
                continue
            ops[rpc] = {
                'method': method.upper(),
                'path': path,
                'status': operation.get('x-reference-status', 'unknown'),
            }
    return ops


def render_fragment(checklist: dict, openapi: dict) -> str:
    entries = checklist['entries']
    ops = load_openapi_ops(openapi)
    status_counts = Counter(entry['referenceStatus'] for entry in entries)
    coverage_counts = Counter(entry['coverage'] for entry in entries)
    linked_tests = sum(len(entry['tests']) for entry in entries)

    lines = [
        '# Generated by tools/render_aggregate_openapi_publisher_fragment.py.',
        '# This file is the publisher-profile-backed fragment synced into spec/openapi.yaml.',
        'externalDocs:',
        '  description: Generated publisher HTTP profile',
        '  url: ./publisher/openapi.json',
        'x-tea-publisher-profile:',
        '  path: spec/publisher/openapi.json',
        '  fragment: spec/generated/publisher-profile-fragment.yaml',
        '  generatedFrom: tools/generate_publisher_openapi.py',
        '  fragmentGenerator: tools/render_aggregate_openapi_publisher_fragment.py',
        '  validator: tools/validate_publisher_openapi.py',
        '  syncTool: tools/sync_aggregate_openapi_publisher_block.py',
        '  canonicalContract: proto/tea/v1/publisher.proto',
        '  conformanceChecklist: spec/publisher/conformance-checklist.json',
        '  exampleDoc: docs/generated/sbom-tools-publisher-profile-examples.md',
        '  reqwestSnippetDoc: docs/generated/sbom-tools-publisher-reqwest-snippets.md',
        'x-tea-publisher-summary:',
        f'  rpcCount: {len(entries)}',
        f'  httpOperationCount: {len(ops)}',
        f'  implemented: {status_counts.get("implemented", 0)}',
        f'  intentionallyUnimplemented: {status_counts.get("intentionally_unimplemented", 0)}',
        f'  directCoverage: {coverage_counts.get("direct", 0)}',
        f'  indirectCoverage: {coverage_counts.get("indirect", 0)}',
        f'  plannedCoverage: {coverage_counts.get("planned", 0)}',
        f'  linkedExecutableTests: {linked_tests}',
        '  generatedFromChecklist: spec/publisher/conformance-checklist.json',
        'x-tea-publisher-rpc-index:',
    ]
    for entry in entries:
        rpc = entry['rpc']
        op = ops.get(rpc)
        lines.extend([
            f'  {rpc}:',
            f'    method: {op["method"] if op else "UNKNOWN"}',
            f'    path: {op["path"] if op else "missing"}',
            f'    referenceStatus: {entry["referenceStatus"]}',
            f'    coverage: {entry["coverage"]}',
            f'    tests: {len(entry["tests"])}',
        ])
    return '\n'.join(lines) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(description='Render the aggregate OpenAPI publisher fragment from canonical publisher inputs')
    parser.add_argument('--check', action='store_true', help='fail if the generated fragment is out of date')
    args = parser.parse_args()

    rendered = render_fragment(load_json(CHECKLIST), load_json(OPENAPI))
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else None
        if current != rendered:
            raise SystemExit('aggregate OpenAPI publisher fragment is out of date; run tools/render_aggregate_openapi_publisher_fragment.py')
        print('aggregate OpenAPI publisher fragment check ok')
        return

    OUTPUT.write_text(rendered)
    print(f'wrote {OUTPUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
