#!/usr/bin/env python3
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRAGMENT = ROOT / 'spec/generated/publisher-profile-fragment.yaml'
AGGREGATE = ROOT / 'spec/openapi.yaml'
START = '# BEGIN GENERATED PUBLISHER PROFILE BLOCK'
END = '# END GENERATED PUBLISHER PROFILE BLOCK'
BLOCK_RE = re.compile(rf'(?ms)^\s*{re.escape(START)}\n.*?^\s*{re.escape(END)}\n?')


def load_fragment() -> str:
    if not FRAGMENT.exists():
        raise SystemExit(f'missing generated fragment {FRAGMENT}; run tools/render_aggregate_openapi_publisher_fragment.py first')
    return FRAGMENT.read_text().rstrip() + '\n'


def replace_block(text: str, fragment: str) -> str:
    if START not in text or END not in text:
        raise SystemExit(f'{AGGREGATE} is missing generated publisher block markers')
    wrapped = '\n'.join([
        START,
        '# This block is generated by tools/sync_aggregate_openapi_publisher_block.py.',
        '# Do not edit it by hand; regenerate spec/generated/publisher-profile-fragment.yaml first.',
        fragment.rstrip(),
        END,
        '',
    ])
    return BLOCK_RE.sub(wrapped, text, count=1)


def main() -> None:
    parser = argparse.ArgumentParser(description='Sync the generated publisher-profile block inside spec/openapi.yaml')
    parser.add_argument('--check', action='store_true', help='fail if spec/openapi.yaml is out of date')
    args = parser.parse_args()

    aggregate_text = AGGREGATE.read_text()
    rendered = replace_block(aggregate_text, load_fragment())

    if args.check:
        if rendered != aggregate_text:
            raise SystemExit('spec/openapi.yaml publisher block is out of date; run tools/render_aggregate_openapi_publisher_block.py')
        print('aggregate OpenAPI publisher block check ok')
        return

    AGGREGATE.write_text(rendered)
    print(f'updated {AGGREGATE.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
